#!/usr/bin/env bun
/**
 * viewer-v2/build-data.ts — same data source as viewer/build-data.ts,
 * but emits into viewer-v2/data.js. Kept parallel so either viewer can be
 * rebuilt independently.
 */

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");

type Scope = {
  id: string;
  label: string;
  kind: "flagship" | "intra";
  provider?: "anthropic" | "openai" | "google" | "xai";
  dir: string;
};

const SCOPES: Scope[] = [
  { id: "flagship",  label: "Speed bench",       kind: "flagship",                           dir: "skills/custom-model-bench/examples/demo" },
  { id: "anthropic", label: "Anthropic tiers",   kind: "intra", provider: "anthropic",       dir: "skills/custom-model-bench/examples/anthropic-tiers" },
  { id: "openai",    label: "OpenAI tiers",      kind: "intra", provider: "openai",          dir: "skills/custom-model-bench/examples/openai-tiers" },
  { id: "google",    label: "Google tiers",      kind: "intra", provider: "google",          dir: "skills/custom-model-bench/examples/google-tiers" },
  { id: "xai",       label: "xAI tiers",         kind: "intra", provider: "xai",             dir: "skills/custom-model-bench/examples/xai-tiers" },
  { id: "reasoning", label: "Reasoning bench",   kind: "flagship",                           dir: "skills/custom-model-bench/examples/reasoning" },
];

async function latestComparisonFile(runsDir: string): Promise<string | null> {
  let entries: string[];
  try {
    entries = await readdir(runsDir);
  } catch {
    return null;
  }
  const files = entries.filter((f) => /^comparison_.*\.json$/.test(f));
  if (files.length === 0) return null;
  const withMtime = await Promise.all(
    files.map(async (f) => ({ p: join(runsDir, f), m: (await stat(join(runsDir, f))).mtimeMs })),
  );
  withMtime.sort((a, b) => b.m - a.m);
  return withMtime[0].p;
}

async function main() {
  const bench: { scopes: any[] } = { scopes: [] };

  for (const scope of SCOPES) {
    const runsDir = join(REPO_ROOT, scope.dir, "runs");
    const latest = await latestComparisonFile(runsDir);
    if (!latest) {
      console.warn(`  [skip] ${scope.id}: no comparison_*.json in ${runsDir}`);
      continue;
    }
    const raw = await readFile(latest, "utf8");
    const data = JSON.parse(raw);
    bench.scopes.push({
      id: scope.id,
      label: scope.label,
      kind: scope.kind,
      provider: scope.provider ?? null,
      comparison: data,
      source_path: latest.replace(REPO_ROOT + "/", ""),
    });
    console.log(`  ${scope.id.padEnd(10)} ← ${latest.replace(REPO_ROOT + "/", "")}`);
  }

  const js =
    `// AUTO-GENERATED by viewer-v2/build-data.ts — do not edit by hand.\n` +
    `// Regenerate with:  bun viewer-v2:build\n\n` +
    `window.__BENCH = ${JSON.stringify(bench, null, 2)};\n`;

  const outPath = join(HERE, "data.js");
  await writeFile(outPath, js, "utf8");
  console.log(
    `\nWrote ${outPath} (${bench.scopes.length} scopes, ${(js.length / 1024).toFixed(1)} KB)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
