#!/usr/bin/env bun
/**
 * viewer-v3/build-data.ts — same data source as viewer-v2/build-data.ts,
 * but emits into viewer-v3/data.js. Kept parallel so any viewer can be
 * rebuilt independently.
 */

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");

type Scope = {
  id: string;
  label: string;
  kind: "flagship" | "intra" | "agentic";
  provider?: "anthropic" | "openai" | "google" | "xai";
  dir: string;
};

const SCOPES: Scope[] = [
  { id: "flagship",     label: "Speed bench",        kind: "flagship", dir: "skills/custom-model-bench/examples/demo" },
  { id: "reasoning",    label: "Reasoning bench",    kind: "flagship", dir: "skills/custom-model-bench/examples/reasoning" },
  { id: "tool-bench",   label: "Tool bench",         kind: "flagship", dir: "skills/custom-model-bench/examples/tool-bench" },
  { id: "yc-qualifier", label: "Prospect qualifier", kind: "agentic",  dir: "skills/custom-model-bench/examples/yc-qualifier" },
];

async function comparisonFilesByMtime(runsDir: string): Promise<{ p: string; m: number }[]> {
  let entries: string[];
  try {
    entries = await readdir(runsDir);
  } catch {
    return [];
  }
  const files = entries.filter((f) => /^comparison_.*\.json$/.test(f));
  if (files.length === 0) return [];
  const withMtime = await Promise.all(
    files.map(async (f) => ({ p: join(runsDir, f), m: (await stat(join(runsDir, f))).mtimeMs })),
  );
  withMtime.sort((a, b) => a.m - b.m); // oldest first
  return withMtime;
}

function slimRun(run: any) {
  return { provider: run.provider, model: run.model, aggregate: run.aggregate };
}

async function main() {
  const bench: { scopes: any[] } = { scopes: [] };

  for (const scope of SCOPES) {
    const runsDir = join(REPO_ROOT, scope.dir, "runs");
    const all = await comparisonFilesByMtime(runsDir);
    if (all.length === 0) {
      console.warn(`  [skip] ${scope.id}: no comparison_*.json in ${runsDir}`);
      continue;
    }
    const latestEntry = all[all.length - 1];
    const rawLatest = await readFile(latestEntry.p, "utf8");
    const latestData = JSON.parse(rawLatest);

    const history: any[] = [];
    for (const entry of all) {
      let data: any;
      if (entry.p === latestEntry.p) {
        data = latestData;
      } else {
        data = JSON.parse(await readFile(entry.p, "utf8"));
      }
      history.push({
        comparison_id: data.comparison_id,
        started_at: data.started_at,
        completed_at: data.completed_at,
        runs: (data.runs || []).map(slimRun),
      });
    }

    bench.scopes.push({
      id: scope.id,
      label: scope.label,
      kind: scope.kind,
      provider: scope.provider ?? null,
      comparison: latestData,
      history,
      source_path: latestEntry.p.replace(REPO_ROOT + "/", ""),
    });
    console.log(
      `  ${scope.id.padEnd(10)} ← ${latestEntry.p.replace(REPO_ROOT + "/", "")} (history: ${history.length})`,
    );
  }

  const js =
    `// AUTO-GENERATED by viewer-v3/build-data.ts — do not edit by hand.\n` +
    `// Regenerate with:  bun viewer-v3:build\n\n` +
    `window.__BENCH = ${JSON.stringify(bench, null, 2)};\n`;

  const outPath = join(HERE, "data.js");
  await writeFile(outPath, js, "utf8");
  console.log(
    `\nWrote ${outPath} (${bench.scopes.length} scopes, ${(js.length / 1024).toFixed(1)} KB)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
